### ISSUE TITLE
Add a way to tell progress along the path

### ISSUE THREAD

**Issue by darzu** [jwunderl/arcade-tilemap-a-star#7]
From @jwunderl:
we could do a starting implementation by just returning a getter for the sprites currentIndex / path length?

**Comment by jwunderl** [comment]
@darzu I added this, but two things I was curious about your opinion on;

* should it be 0-1 or 0-100 for percentage? I picked the second to match ``Math.percentChance``
* when a sprite is not following a path, what should the return value be? I picked 100, under the reasoning that if a sprite is not following a path, it has trivially 'completed' whatever it's following -- which keeps it consistent after the sprite has completed it's path as it will be removed from the list.

If you disagree on any of these feel free to change, I don't have strong opinions on them~
